/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TShareIdRouteImport } from './routes/t.$shareId'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppTeamsRouteImport } from './routes/app.teams'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppAudiencesRouteImport } from './routes/app.audiences'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTrainingsRouteImport } from './routes/admin/trainings'
import { Route as AdminTestsRouteImport } from './routes/admin/tests'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminShareCardRouteImport } from './routes/admin/share-card'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRespondentsRouteImport } from './routes/admin/respondents'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminQuickTestRouteImport } from './routes/admin/quick-test'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminHeaderRouteImport } from './routes/admin/header'
import { Route as AdminFooterRouteImport } from './routes/admin/footer'
import { Route as AdminDsrRouteImport } from './routes/admin/dsr'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAnswerSetsRouteImport } from './routes/admin/answer-sets'
import { Route as AppTestsIndexRouteImport } from './routes/app.tests.index'
import { Route as AppTestsNewRouteImport } from './routes/app.tests.new'
import { Route as AppTestsTestIdRouteImport } from './routes/app.tests.$testId'
import { Route as AppSetsSetIdRouteImport } from './routes/app.sets.$setId'
import { Route as AppLegalDsrRouteImport } from './routes/app.legal.dsr'
import { Route as AppAccountSecurityRouteImport } from './routes/app.account.security'
import { Route as AppAccountProfileRouteImport } from './routes/app.account.profile'
import { Route as AdminTestsTestIdRouteImport } from './routes/admin/tests.$testId'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin/pages.$pageId'
import { Route as AdminAnswerSetsSetIdRouteImport } from './routes/admin/answer-sets.$setId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TShareIdRoute = TShareIdRouteImport.update({
  id: '/t/$shareId',
  path: '/t/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppAudiencesRoute = AppAudiencesRouteImport.update({
  id: '/audiences',
  path: '/audiences',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingsRoute = AdminTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestsRoute = AdminTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShareCardRoute = AdminShareCardRouteImport.update({
  id: '/share-card',
  path: '/share-card',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRespondentsRoute = AdminRespondentsRouteImport.update({
  id: '/respondents',
  path: '/respondents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuickTestRoute = AdminQuickTestRouteImport.update({
  id: '/quick-test',
  path: '/quick-test',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeaderRoute = AdminHeaderRouteImport.update({
  id: '/header',
  path: '/header',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDsrRoute = AdminDsrRouteImport.update({
  id: '/dsr',
  path: '/dsr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnswerSetsRoute = AdminAnswerSetsRouteImport.update({
  id: '/answer-sets',
  path: '/answer-sets',
  getParentRoute: () => AdminRoute,
} as any)
const AppTestsIndexRoute = AppTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsNewRoute = AppTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsTestIdRoute = AppTestsTestIdRouteImport.update({
  id: '/tests/$testId',
  path: '/tests/$testId',
  getParentRoute: () => AppRoute,
} as any)
const AppSetsSetIdRoute = AppSetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalDsrRoute = AppLegalDsrRouteImport.update({
  id: '/legal/dsr',
  path: '/legal/dsr',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountSecurityRoute = AppAccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => AppRoute,
} as any)
const AdminTestsTestIdRoute = AdminTestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => AdminTestsRoute,
} as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminAnswerSetsSetIdRoute = AdminAnswerSetsSetIdRouteImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => AdminAnswerSetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/answer-sets': typeof AdminAnswerSetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dsr': typeof AdminDsrRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/quick-test': typeof AdminQuickTestRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/respondents': typeof AdminRespondentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/share-card': typeof AdminShareCardRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tests': typeof AdminTestsRouteWithChildren
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/audiences': typeof AppAudiencesRoute
  '/app/help': typeof AppHelpRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/s/$slug': typeof SSlugRoute
  '/t/$shareId': typeof TShareIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/answer-sets/$setId': typeof AdminAnswerSetsSetIdRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/tests/$testId': typeof AdminTestsTestIdRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/legal/dsr': typeof AppLegalDsrRoute
  '/app/sets/$setId': typeof AppSetsSetIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/app/tests/': typeof AppTestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/answer-sets': typeof AdminAnswerSetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dsr': typeof AdminDsrRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/quick-test': typeof AdminQuickTestRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/respondents': typeof AdminRespondentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/share-card': typeof AdminShareCardRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tests': typeof AdminTestsRouteWithChildren
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/audiences': typeof AppAudiencesRoute
  '/app/help': typeof AppHelpRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/s/$slug': typeof SSlugRoute
  '/t/$shareId': typeof TShareIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/answer-sets/$setId': typeof AdminAnswerSetsSetIdRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/tests/$testId': typeof AdminTestsTestIdRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/legal/dsr': typeof AppLegalDsrRoute
  '/app/sets/$setId': typeof AppSetsSetIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/app/tests': typeof AppTestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/answer-sets': typeof AdminAnswerSetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dsr': typeof AdminDsrRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/quick-test': typeof AdminQuickTestRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/respondents': typeof AdminRespondentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/share-card': typeof AdminShareCardRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tests': typeof AdminTestsRouteWithChildren
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/audiences': typeof AppAudiencesRoute
  '/app/help': typeof AppHelpRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/s/$slug': typeof SSlugRoute
  '/t/$shareId': typeof TShareIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/answer-sets/$setId': typeof AdminAnswerSetsSetIdRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/tests/$testId': typeof AdminTestsTestIdRoute
  '/app/account/profile': typeof AppAccountProfileRoute
  '/app/account/security': typeof AppAccountSecurityRoute
  '/app/legal/dsr': typeof AppLegalDsrRoute
  '/app/sets/$setId': typeof AppSetsSetIdRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/tests/new': typeof AppTestsNewRoute
  '/app/tests/': typeof AppTestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/app'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/answer-sets'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dsr'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/questions'
    | '/admin/quick-test'
    | '/admin/reports'
    | '/admin/respondents'
    | '/admin/settings'
    | '/admin/share-card'
    | '/admin/support'
    | '/admin/tests'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/audiences'
    | '/app/help'
    | '/app/history'
    | '/app/library'
    | '/app/notifications'
    | '/app/teams'
    | '/app/templates'
    | '/s/$slug'
    | '/t/$shareId'
    | '/admin/'
    | '/app/'
    | '/admin/answer-sets/$setId'
    | '/admin/pages/$pageId'
    | '/admin/tests/$testId'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/legal/dsr'
    | '/app/sets/$setId'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/app/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/answer-sets'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dsr'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/questions'
    | '/admin/quick-test'
    | '/admin/reports'
    | '/admin/respondents'
    | '/admin/settings'
    | '/admin/share-card'
    | '/admin/support'
    | '/admin/tests'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/audiences'
    | '/app/help'
    | '/app/history'
    | '/app/library'
    | '/app/notifications'
    | '/app/teams'
    | '/app/templates'
    | '/s/$slug'
    | '/t/$shareId'
    | '/admin'
    | '/app'
    | '/admin/answer-sets/$setId'
    | '/admin/pages/$pageId'
    | '/admin/tests/$testId'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/legal/dsr'
    | '/app/sets/$setId'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/app/tests'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/app'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/answer-sets'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dsr'
    | '/admin/footer'
    | '/admin/header'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/questions'
    | '/admin/quick-test'
    | '/admin/reports'
    | '/admin/respondents'
    | '/admin/settings'
    | '/admin/share-card'
    | '/admin/support'
    | '/admin/tests'
    | '/admin/trainings'
    | '/admin/users'
    | '/app/audiences'
    | '/app/help'
    | '/app/history'
    | '/app/library'
    | '/app/notifications'
    | '/app/teams'
    | '/app/templates'
    | '/s/$slug'
    | '/t/$shareId'
    | '/admin/'
    | '/app/'
    | '/admin/answer-sets/$setId'
    | '/admin/pages/$pageId'
    | '/admin/tests/$testId'
    | '/app/account/profile'
    | '/app/account/security'
    | '/app/legal/dsr'
    | '/app/sets/$setId'
    | '/app/tests/$testId'
    | '/app/tests/new'
    | '/app/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SSlugRoute: typeof SSlugRoute
  TShareIdRoute: typeof TShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/t/$shareId': {
      id: '/t/$shareId'
      path: '/t/$shareId'
      fullPath: '/t/$shareId'
      preLoaderRoute: typeof TShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teams': {
      id: '/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audiences': {
      id: '/app/audiences'
      path: '/audiences'
      fullPath: '/app/audiences'
      preLoaderRoute: typeof AppAudiencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trainings': {
      id: '/admin/trainings'
      path: '/trainings'
      fullPath: '/admin/trainings'
      preLoaderRoute: typeof AdminTrainingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tests': {
      id: '/admin/tests'
      path: '/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/share-card': {
      id: '/admin/share-card'
      path: '/share-card'
      fullPath: '/admin/share-card'
      preLoaderRoute: typeof AdminShareCardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/respondents': {
      id: '/admin/respondents'
      path: '/respondents'
      fullPath: '/admin/respondents'
      preLoaderRoute: typeof AdminRespondentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quick-test': {
      id: '/admin/quick-test'
      path: '/quick-test'
      fullPath: '/admin/quick-test'
      preLoaderRoute: typeof AdminQuickTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/header': {
      id: '/admin/header'
      path: '/header'
      fullPath: '/admin/header'
      preLoaderRoute: typeof AdminHeaderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dsr': {
      id: '/admin/dsr'
      path: '/dsr'
      fullPath: '/admin/dsr'
      preLoaderRoute: typeof AdminDsrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/answer-sets': {
      id: '/admin/answer-sets'
      path: '/answer-sets'
      fullPath: '/admin/answer-sets'
      preLoaderRoute: typeof AdminAnswerSetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/tests/': {
      id: '/app/tests/'
      path: '/tests'
      fullPath: '/app/tests/'
      preLoaderRoute: typeof AppTestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tests/new': {
      id: '/app/tests/new'
      path: '/tests/new'
      fullPath: '/app/tests/new'
      preLoaderRoute: typeof AppTestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tests/$testId': {
      id: '/app/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/app/tests/$testId'
      preLoaderRoute: typeof AppTestsTestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sets/$setId': {
      id: '/app/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/app/sets/$setId'
      preLoaderRoute: typeof AppSetsSetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/legal/dsr': {
      id: '/app/legal/dsr'
      path: '/legal/dsr'
      fullPath: '/app/legal/dsr'
      preLoaderRoute: typeof AppLegalDsrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account/security': {
      id: '/app/account/security'
      path: '/account/security'
      fullPath: '/app/account/security'
      preLoaderRoute: typeof AppAccountSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account/profile': {
      id: '/app/account/profile'
      path: '/account/profile'
      fullPath: '/app/account/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tests/$testId': {
      id: '/admin/tests/$testId'
      path: '/$testId'
      fullPath: '/admin/tests/$testId'
      preLoaderRoute: typeof AdminTestsTestIdRouteImport
      parentRoute: typeof AdminTestsRoute
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/answer-sets/$setId': {
      id: '/admin/answer-sets/$setId'
      path: '/$setId'
      fullPath: '/admin/answer-sets/$setId'
      preLoaderRoute: typeof AdminAnswerSetsSetIdRouteImport
      parentRoute: typeof AdminAnswerSetsRoute
    }
  }
}

interface AdminAnswerSetsRouteChildren {
  AdminAnswerSetsSetIdRoute: typeof AdminAnswerSetsSetIdRoute
}

const AdminAnswerSetsRouteChildren: AdminAnswerSetsRouteChildren = {
  AdminAnswerSetsSetIdRoute: AdminAnswerSetsSetIdRoute,
}

const AdminAnswerSetsRouteWithChildren = AdminAnswerSetsRoute._addFileChildren(
  AdminAnswerSetsRouteChildren,
)

interface AdminPagesRouteChildren {
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminTestsRouteChildren {
  AdminTestsTestIdRoute: typeof AdminTestsTestIdRoute
}

const AdminTestsRouteChildren: AdminTestsRouteChildren = {
  AdminTestsTestIdRoute: AdminTestsTestIdRoute,
}

const AdminTestsRouteWithChildren = AdminTestsRoute._addFileChildren(
  AdminTestsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnswerSetsRoute: typeof AdminAnswerSetsRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDsrRoute: typeof AdminDsrRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminHeaderRoute: typeof AdminHeaderRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminQuickTestRoute: typeof AdminQuickTestRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRespondentsRoute: typeof AdminRespondentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShareCardRoute: typeof AdminShareCardRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTestsRoute: typeof AdminTestsRouteWithChildren
  AdminTrainingsRoute: typeof AdminTrainingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnswerSetsRoute: AdminAnswerSetsRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDsrRoute: AdminDsrRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminHeaderRoute: AdminHeaderRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminQuickTestRoute: AdminQuickTestRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRespondentsRoute: AdminRespondentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShareCardRoute: AdminShareCardRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTestsRoute: AdminTestsRouteWithChildren,
  AdminTrainingsRoute: AdminTrainingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAudiencesRoute: typeof AppAudiencesRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountSecurityRoute: typeof AppAccountSecurityRoute
  AppLegalDsrRoute: typeof AppLegalDsrRoute
  AppSetsSetIdRoute: typeof AppSetsSetIdRoute
  AppTestsTestIdRoute: typeof AppTestsTestIdRoute
  AppTestsNewRoute: typeof AppTestsNewRoute
  AppTestsIndexRoute: typeof AppTestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAudiencesRoute: AppAudiencesRoute,
  AppHelpRoute: AppHelpRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountSecurityRoute: AppAccountSecurityRoute,
  AppLegalDsrRoute: AppLegalDsrRoute,
  AppSetsSetIdRoute: AppSetsSetIdRoute,
  AppTestsTestIdRoute: AppTestsTestIdRoute,
  AppTestsNewRoute: AppTestsNewRoute,
  AppTestsIndexRoute: AppTestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SSlugRoute: SSlugRoute,
  TShareIdRoute: TShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
