export const ROUTES = {
  home: "/",
  test: "/test",
  testy: "/testy",
  testySlug: "/testy/$slug",
  zostav: "/test/zostav",
  zostava: "/test/zostava/$id",
  skolenia: "/skolenia",
  skoleniaSlug: "/skolenia/$slug",
  podpora: "/podpora",
  sponzori: "/sponzori",
  sponzoriVsetci: "/sponzori/vsetci",
  spravovat: "/spravovat-podporu",
  privacy: "/privacy",
  cookies: "/cookies",
  oProjecte: "/o-projekte",
  zmeny: "/zmeny",
  kontakt: "/kontakt",
} as const;
