/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KurzyIndexRouteImport } from './routes/kurzy.index'
import { Route as RShareIdRouteImport } from './routes/r.$shareId'
import { Route as KurzySlugRouteImport } from './routes/kurzy.$slug'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KurzyIndexRoute = KurzyIndexRouteImport.update({
  id: '/kurzy/',
  path: '/kurzy/',
  getParentRoute: () => rootRouteImport,
} as any)
const RShareIdRoute = RShareIdRouteImport.update({
  id: '/r/$shareId',
  path: '/r/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const KurzySlugRoute = KurzySlugRouteImport.update({
  id: '/kurzy/$slug',
  path: '/kurzy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/test': typeof TestRoute
  '/kurzy/$slug': typeof KurzySlugRoute
  '/r/$shareId': typeof RShareIdRoute
  '/kurzy/': typeof KurzyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/test': typeof TestRoute
  '/kurzy/$slug': typeof KurzySlugRoute
  '/r/$shareId': typeof RShareIdRoute
  '/kurzy': typeof KurzyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/test': typeof TestRoute
  '/kurzy/$slug': typeof KurzySlugRoute
  '/r/$shareId': typeof RShareIdRoute
  '/kurzy/': typeof KurzyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/test'
    | '/kurzy/$slug'
    | '/r/$shareId'
    | '/kurzy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/test'
    | '/kurzy/$slug'
    | '/r/$shareId'
    | '/kurzy'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/privacy'
    | '/test'
    | '/kurzy/$slug'
    | '/r/$shareId'
    | '/kurzy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  TestRoute: typeof TestRoute
  KurzySlugRoute: typeof KurzySlugRoute
  RShareIdRoute: typeof RShareIdRoute
  KurzyIndexRoute: typeof KurzyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurzy/': {
      id: '/kurzy/'
      path: '/kurzy'
      fullPath: '/kurzy/'
      preLoaderRoute: typeof KurzyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$shareId': {
      id: '/r/$shareId'
      path: '/r/$shareId'
      fullPath: '/r/$shareId'
      preLoaderRoute: typeof RShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurzy/$slug': {
      id: '/kurzy/$slug'
      path: '/kurzy/$slug'
      fullPath: '/kurzy/$slug'
      preLoaderRoute: typeof KurzySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  TestRoute: TestRoute,
  KurzySlugRoute: KurzySlugRoute,
  RShareIdRoute: RShareIdRoute,
  KurzyIndexRoute: KurzyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
