/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PodporaRouteImport } from './routes/podpora'
import { Route as OProjekteRouteImport } from './routes/o-projekte'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test.index'
import { Route as SkoleniaIndexRouteImport } from './routes/skolenia.index'
import { Route as SkoleniaSlugRouteImport } from './routes/skolenia.$slug'
import { Route as RShareIdRouteImport } from './routes/r.$shareId'
import { Route as TestFirmaIndexRouteImport } from './routes/test.firma.index'
import { Route as TestFirmaSlugRouteImport } from './routes/test.firma.$slug'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PodporaRoute = PodporaRouteImport.update({
  id: '/podpora',
  path: '/podpora',
  getParentRoute: () => rootRouteImport,
} as any)
const OProjekteRoute = OProjekteRouteImport.update({
  id: '/o-projekte',
  path: '/o-projekte',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkoleniaIndexRoute = SkoleniaIndexRouteImport.update({
  id: '/skolenia/',
  path: '/skolenia/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkoleniaSlugRoute = SkoleniaSlugRouteImport.update({
  id: '/skolenia/$slug',
  path: '/skolenia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RShareIdRoute = RShareIdRouteImport.update({
  id: '/r/$shareId',
  path: '/r/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFirmaIndexRoute = TestFirmaIndexRouteImport.update({
  id: '/test/firma/',
  path: '/test/firma/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestFirmaSlugRoute = TestFirmaSlugRouteImport.update({
  id: '/test/firma/$slug',
  path: '/test/firma/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/o-projekte': typeof OProjekteRoute
  '/podpora': typeof PodporaRoute
  '/privacy': typeof PrivacyRoute
  '/r/$shareId': typeof RShareIdRoute
  '/skolenia/$slug': typeof SkoleniaSlugRoute
  '/skolenia/': typeof SkoleniaIndexRoute
  '/test/': typeof TestIndexRoute
  '/test/firma/$slug': typeof TestFirmaSlugRoute
  '/test/firma/': typeof TestFirmaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/o-projekte': typeof OProjekteRoute
  '/podpora': typeof PodporaRoute
  '/privacy': typeof PrivacyRoute
  '/r/$shareId': typeof RShareIdRoute
  '/skolenia/$slug': typeof SkoleniaSlugRoute
  '/skolenia': typeof SkoleniaIndexRoute
  '/test': typeof TestIndexRoute
  '/test/firma/$slug': typeof TestFirmaSlugRoute
  '/test/firma': typeof TestFirmaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/o-projekte': typeof OProjekteRoute
  '/podpora': typeof PodporaRoute
  '/privacy': typeof PrivacyRoute
  '/r/$shareId': typeof RShareIdRoute
  '/skolenia/$slug': typeof SkoleniaSlugRoute
  '/skolenia/': typeof SkoleniaIndexRoute
  '/test/': typeof TestIndexRoute
  '/test/firma/$slug': typeof TestFirmaSlugRoute
  '/test/firma/': typeof TestFirmaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/o-projekte'
    | '/podpora'
    | '/privacy'
    | '/r/$shareId'
    | '/skolenia/$slug'
    | '/skolenia/'
    | '/test/'
    | '/test/firma/$slug'
    | '/test/firma/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/o-projekte'
    | '/podpora'
    | '/privacy'
    | '/r/$shareId'
    | '/skolenia/$slug'
    | '/skolenia'
    | '/test'
    | '/test/firma/$slug'
    | '/test/firma'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/o-projekte'
    | '/podpora'
    | '/privacy'
    | '/r/$shareId'
    | '/skolenia/$slug'
    | '/skolenia/'
    | '/test/'
    | '/test/firma/$slug'
    | '/test/firma/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  OProjekteRoute: typeof OProjekteRoute
  PodporaRoute: typeof PodporaRoute
  PrivacyRoute: typeof PrivacyRoute
  RShareIdRoute: typeof RShareIdRoute
  SkoleniaSlugRoute: typeof SkoleniaSlugRoute
  SkoleniaIndexRoute: typeof SkoleniaIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  TestFirmaSlugRoute: typeof TestFirmaSlugRoute
  TestFirmaIndexRoute: typeof TestFirmaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podpora': {
      id: '/podpora'
      path: '/podpora'
      fullPath: '/podpora'
      preLoaderRoute: typeof PodporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-projekte': {
      id: '/o-projekte'
      path: '/o-projekte'
      fullPath: '/o-projekte'
      preLoaderRoute: typeof OProjekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skolenia/': {
      id: '/skolenia/'
      path: '/skolenia'
      fullPath: '/skolenia/'
      preLoaderRoute: typeof SkoleniaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skolenia/$slug': {
      id: '/skolenia/$slug'
      path: '/skolenia/$slug'
      fullPath: '/skolenia/$slug'
      preLoaderRoute: typeof SkoleniaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$shareId': {
      id: '/r/$shareId'
      path: '/r/$shareId'
      fullPath: '/r/$shareId'
      preLoaderRoute: typeof RShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/firma/': {
      id: '/test/firma/'
      path: '/test/firma'
      fullPath: '/test/firma/'
      preLoaderRoute: typeof TestFirmaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/firma/$slug': {
      id: '/test/firma/$slug'
      path: '/test/firma/$slug'
      fullPath: '/test/firma/$slug'
      preLoaderRoute: typeof TestFirmaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  OProjekteRoute: OProjekteRoute,
  PodporaRoute: PodporaRoute,
  PrivacyRoute: PrivacyRoute,
  RShareIdRoute: RShareIdRoute,
  SkoleniaSlugRoute: SkoleniaSlugRoute,
  SkoleniaIndexRoute: SkoleniaIndexRoute,
  TestIndexRoute: TestIndexRoute,
  TestFirmaSlugRoute: TestFirmaSlugRoute,
  TestFirmaIndexRoute: TestFirmaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
